// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;
using System.Runtime.CompilerServices;

[assembly:InternalsVisibleTo("UABE_2_1d_x86")]

namespace StdDelegate
{
    namespace CompressedPair
    {
        [StructLayout(LayoutKind.Explicit, Size = 12)]
        public unsafe partial struct __Internalc__N_std_S__Compressed_pair____N_std_S_allocator____S_ClassDatabaseTypeField___N_std_S__Vector_val____N_std_S__Simple_types__S1__Vb1
        {
            [FieldOffset(0)]
            internal global::StdDelegate.VectorVal.__Internal _Myval2;
        }

        [StructLayout(LayoutKind.Explicit, Size = 12)]
        public unsafe partial struct __Internalc__N_std_S__Compressed_pair____N_std_S_allocator____S_ClassDatabaseType___N_std_S__Vector_val____N_std_S__Simple_types__S1__Vb1
        {
            [FieldOffset(0)]
            internal global::StdDelegate.VectorVal.__Internal _Myval2;
        }
    }
}

namespace StdDelegate
{
}

namespace StdDelegate
{
    namespace Vector
    {
        [StructLayout(LayoutKind.Explicit, Size = 12)]
        public unsafe partial struct __Internalc__N_std_S_vector____S_ClassDatabaseType___N_std_S_allocator__S0_
        {
            [FieldOffset(0)]
            internal global::StdDelegate.CompressedPair.__Internalc__N_std_S__Compressed_pair____N_std_S_allocator____S_ClassDatabaseType___N_std_S__Vector_val____N_std_S__Simple_types__S1__Vb1 _Mypair;
        }

        [StructLayout(LayoutKind.Explicit, Size = 12)]
        public unsafe partial struct __Internalc__N_std_S_vector____S_ClassDatabaseTypeField___N_std_S_allocator__S0_
        {
            [FieldOffset(0)]
            internal global::StdDelegate.CompressedPair.__Internalc__N_std_S__Compressed_pair____N_std_S_allocator____S_ClassDatabaseTypeField___N_std_S__Vector_val____N_std_S__Simple_types__S1__Vb1 _Mypair;
        }
    }

    namespace VectorVal
    {
        [StructLayout(LayoutKind.Explicit, Size = 12)]
        public unsafe partial struct __Internal
        {
            [FieldOffset(0)]
            internal global::System.IntPtr _Myfirst;

            [FieldOffset(4)]
            internal global::System.IntPtr _Mylast;

            [FieldOffset(8)]
            internal global::System.IntPtr _Myend;
        }
    }
}
